#http
version: "3.7"

services:
    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: always
        ports:
            - "8001:8000"
            - "9443:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    portainer_data:
